### ISSUE TITLE
[ Bug ] : File name is too long AND file is without extension (Details Inside)

### ISSUE THREAD

**Issue by NomanBaigA** [kecav/igdownloader#2]
When I try to download something chrome says the "file name is too long" and it doesn't contain any extension.
It should directly download the file with the proper extension.

Except this bug, the project is amazing and I really like it. Thanks for this.

**Comment by kecav** [comment]
Hey @NomanBaigA, I truly appreciate your feedback. Regarding the issue that you've pointed, i tried  solving it but it turns out, the api that I'm using doesn't allow download because of CORs. Although I'm still trying to figure it out. 

If i reach the solution, will update it asap.

**Comment by NomanBaigA** [comment]
> Hey @NomanBaigA, I truly appreciate your feedback. Regarding the issue that you've pointed, i tried solving it but it turns out, the api that I'm using doesn't allow download because of CORs. Although I'm still trying to figure it out.
> 
> If i reach the solution, will update it asap.

everything is working properly bro... the problem is only with file name and extension

**Comment by NomanBaigA** [comment]
> Hey @NomanBaigA, I truly appreciate your feedback. Regarding the issue that you've pointed, i tried solving it but it turns out, the api that I'm using doesn't allow download because of CORs. Although I'm still trying to figure it out.
> 
> If i reach the solution, will update it asap.

maybe this is helpful for you - https://github.com/awesome-yasin/Media-Downloader
.
the Instagram part is mostly the same there but it downloads the file with a small name and proper extension.
